### ISSUE TITLE
trailing slash

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-nuxt-template#12]
- [ ] add this to our docs/template whatever

![Screenshot 2024-09-10 at 17 28 32](https://github.com/user-attachments/assets/063f324d-032d-483d-bbe2-611472aede51)

**Comment by devinschumacher** [comment]
@dawaltconley what about links that we define statically? or maybe we shouldnt even do that as a best practice? have you read anything on this?

**Comment by dawaltconley** [comment]
@dawaltconley I'm going to close this as complete. I think it's not trivial to lint for non-trailing slashes in CICD (how do we identify links? we could look for `href`s but they appear in other places: unique components, refs, config files. we'd also have to distinguish from external links, which should not all have trialing slashes.)

Currently the config is set up so that trailing slashes will be enforced (automatically added) on all links created with the `NuxtLink` or NuxtSeo's `SiteLink` component, which is what we should use for all internal links. I'm adding a note in the README about this component.

**Comment by devinschumacher** [comment]
> @dawaltconley I'm going to close this as complete. I think it's not trivial to lint for non-trailing slashes in CICD (how do we identify links? we could look for `href`s but they appear in other places: unique components, refs, config files. we'd also have to distinguish from external links, which should not all have trialing slashes.)
> 
> Currently the config is set up so that trailing slashes will be enforced (automatically added) on all links created with the `NuxtLink` or NuxtSeo's `SiteLink` component, which is what we should use for all internal links. I'm adding a note in the README about this component.


okay so i believe a best practice is to just use <NuxtLink> component for all internal AND external links on the site anyways. and if we are doing that, and using the nuxt.config.ts setting to append trailing slashes, we should be fine.
